# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 03:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ladders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('player_a_score', models.IntegerField()),
                ('player_b_score', models.IntegerField()),
                ('match_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ladder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ladders.Ladder')),
                ('player_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_a', to=settings.AUTH_USER_MODEL)),
                ('player_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_b', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
