# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-15 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_auto_20160121_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='ladder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ladders.Ladder'),
        ),
    ]
