# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-18 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_auto_20160515_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='alternate_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='is_challenge_match',
            field=models.BooleanField(default=False),
        ),
    ]
