# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-05 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_auto_20160518_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
