# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_ladder',
            name='ladder_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
