# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-22 02:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ladders', '0002_user_ladder_ladder_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='ladder',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user_ladder',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
