# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-24 22:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ladders', '0004_auto_20160422_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ladder',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
