# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-15 18:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ladders', '0006_auto_20160515_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ladder',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 15, 18, 42, 47, 106586, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ladder',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 15, 18, 43, 1, 818450, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
